# syntax=docker/dockerfile:1
FROM python:3.11.4-slim-bookworm
ENV FLASK_APP=app:app

WORKDIR /app

COPY . .
RUN bash -c 'pip install --upgrade pip'
RUN pip install -r requirements.txt
RUN bash -c 'python init_db.py'

EXPOSE 8000

CMD [ "flask","run","--host=0.0.0.0","--port=8000" ]

